### PR TITLE
Unify NMF packaging and integrate IPK packaging

### PR DESCRIPTION
**Pull request by yannickl96**
This pull request addresses the following issues:
* Feature #448: Integrate OPS-SAT SEPP IPK packaging into nmf-mission-ops-sat build
* Feature #493: Unify NMF packaging environment variables

## Feature #448: Integrate OPS-SAT SEPP IPK packaging into nmf-mission-ops-sat build
**Goal:** Create an IPK package during Maven build which can be deployed on the SEPP.
**Implementation:** Use the Maven Antrun Plugin to copy the files and tar them into the archive.

## Feature #493: Unify NMF packaging environment variables
**Goal:** Synchronize the directory structure and start scripts of the SDK with the structure and start scripts used on OPS-SAT.
**Implementation**: Add NMF_HOME to the start script and add logging.properties which causes log files local to the applications/apps execution directory.

### CODE REVIEW

**Comment by dmarszk** [comment]
IPK should also deploy nmf-supervisor as a systemd service - check spp bridge for reference.

**Comment by yannickl96** [comment]
This should work, or do I need to update the supervisor script to change the execution directory to the supervisor folder?

**Comment by dmarszk** [comment]
- workdir should be set
- prerm should include service stopping and disabling

**Comment by yannickl96** [comment]
Implemented.

**Pull request merged**
